/**
 * Vidzee - Nuvio provider (v3, rebuilt against core.vidzee.wtf API)
 *
 * Old /api/server?id=&sr= endpoints are gone. Vidzee's player now:
 *
 *   1. GET https://core.vidzee.wtf/streams/languages/movie/{tmdbId}
 *        or /streams/languages/tv/{tmdbId}/{season}/{episode}
 *        -> { "languages": ["Hindi","English",...] }
 *   2. server list = ["dcloud"] + languages.map(l => "v4:" + l)
 *   3. GET https://core.vidzee.wtf/streams/{movie|tv}/{tmdbId}[/{s}/{e}]?s={server}&e=1
 *        -> { "c": "<base64 ciphertext>" }
 *   4. ciphertext is decrypted by a small WASM module shipped inside the
 *      player bundle: decrypt(payloadBytes, "player.vidzee.wtf") -> JSON text
 *        { "language": "...", "url": "https://.../index.m3u8",
 *          "headers": { "Referer": "https://..." } }
 *
 * Nuvio's QuickJS runtime has no WebAssembly, so this file embeds the same
 * module compiled to pure ES5 JavaScript (binaryen wasm2js) plus the exact
 * AssemblyScript loader shim the player uses. Decrypt takes ~2ms.
 *
 * Pure ES5 + typed arrays + fetch only: QuickJS / Nuvio TV worker safe.
 */

// ---------------------------------------------------------------------------
// Embedded WASM-to-JS decryptor (generated by binaryen wasm2js from the
// player's own module; exports decrypt/__new/__pin/__unpin/memory)
// ---------------------------------------------------------------------------
function makeVidzeeCrypto() {
var V = {};
var env = { abort: function(A,B,C,I){ throw new Error('abort'); } };

  var bufferView;
  var base64ReverseLookup = new Uint8Array(123/*'z'+1*/);
  for (var i = 25; i >= 0; --i) {
    base64ReverseLookup[48+i] = 52+i; // '0-9'
    base64ReverseLookup[65+i] = i; // 'A-Z'
    base64ReverseLookup[97+i] = 26+i; // 'a-z'
  }
  base64ReverseLookup[43] = 62; // '+'
  base64ReverseLookup[47] = 63; // '/'
  /** @noinline Inlining this function would mean expanding the base64 string 4x times in the source code, which Closure seems to be happy to do. */
  function base64DecodeToExistingUint8Array(uint8Array, offset, b64) {
    var b1, b2, i = 0, j = offset, bLength = b64.length, end = offset + (bLength*3>>2) - (b64[bLength-2] == '=') - (b64[bLength-1] == '=');
    for (; i < bLength; i += 4) {
      b1 = base64ReverseLookup[b64.charCodeAt(i+1)];
      b2 = base64ReverseLookup[b64.charCodeAt(i+2)];
      uint8Array[j++] = base64ReverseLookup[b64.charCodeAt(i)] << 2 | b1 >> 4;
      if (j < end) uint8Array[j++] = b1 << 4 | b2 >> 2;
      if (j < end) uint8Array[j++] = b2 << 6 | base64ReverseLookup[b64.charCodeAt(i+3)];
    }
  }
function initActiveSegments(imports) {
  base64DecodeToExistingUint8Array(bufferView, 1036, "PA==");
  base64DecodeToExistingUint8Array(bufferView, 1048, "AQAAACAAAADk+bJ9jBpu9QN9uYrFTiHwudbDp4H+Qq1lwOm3PxSKLQ==");
  base64DecodeToExistingUint8Array(bufferView, 1100, "LA==");
  base64DecodeToExistingUint8Array(bufferView, 1112, "BAAAABAAAAAgBAAAIAQAACAAAAAg");
  base64DecodeToExistingUint8Array(bufferView, 1148, "PA==");
  base64DecodeToExistingUint8Array(bufferView, 1160, "AgAAACIAAABwAGwAYQB5AGUAcgAuAHYAaQBkAHoAZQBlAC4AdwB0AGY=");
  base64DecodeToExistingUint8Array(bufferView, 1212, "LA==");
  base64DecodeToExistingUint8Array(bufferView, 1224, "AgAAABIAAABsAG8AYwBhAGwAaABvAHMAdA==");
  base64DecodeToExistingUint8Array(bufferView, 1260, "LA==");
  base64DecodeToExistingUint8Array(bufferView, 1272, "AgAAABIAAAAxADIANwAuADAALgAwAC4AMQ==");
  base64DecodeToExistingUint8Array(bufferView, 1308, "HA==");
  base64DecodeToExistingUint8Array(bufferView, 1320, "AQAAAAwAAACQBAAA0AQAAAAF");
  base64DecodeToExistingUint8Array(bufferView, 1340, "LA==");
  base64DecodeToExistingUint8Array(bufferView, 1352, "BQAAABAAAAAwBQAAMAUAAAwAAAAD");
  base64DecodeToExistingUint8Array(bufferView, 1388, "LA==");
  base64DecodeToExistingUint8Array(bufferView, 1400, "AgAAABgAAAAuAGwAbwB2AGEAYgBsAGUALgBhAHAAcA==");
  base64DecodeToExistingUint8Array(bufferView, 1436, "PA==");
  base64DecodeToExistingUint8Array(bufferView, 1448, "AgAAACYAAAAuAGwAbwB2AGEAYgBsAGUAcAByAG8AagBlAGMAdAAuAGMAbwBt");
  base64DecodeToExistingUint8Array(bufferView, 1500, "LA==");
  base64DecodeToExistingUint8Array(bufferView, 1512, "AgAAABYAAAAuAHYAaQBkAHoAZQBlAC4AdwB0AGY=");
  base64DecodeToExistingUint8Array(bufferView, 1548, "HA==");
  base64DecodeToExistingUint8Array(bufferView, 1560, "AQAAAAwAAACABQAAsAUAAPAF");
  base64DecodeToExistingUint8Array(bufferView, 1580, "LA==");
  base64DecodeToExistingUint8Array(bufferView, 1592, "BQAAABAAAAAgBgAAIAYAAAwAAAAD");
  base64DecodeToExistingUint8Array(bufferView, 1628, "PA==");
  base64DecodeToExistingUint8Array(bufferView, 1640, "AgAAACgAAABBAGwAbABvAGMAYQB0AGkAbwBuACAAdABvAG8AIABsAGEAcgBnAGU=");
  base64DecodeToExistingUint8Array(bufferView, 1692, "PA==");
  base64DecodeToExistingUint8Array(bufferView, 1704, "AgAAAB4AAAB+AGwAaQBiAC8AcgB0AC8AdABjAG0AcwAuAHQAcw==");
  base64DecodeToExistingUint8Array(bufferView, 1756, "PA==");
  base64DecodeToExistingUint8Array(bufferView, 1768, "AgAAAB4AAAB+AGwAaQBiAC8AcgB0AC8AdABsAHMAZgAuAHQAcw==");
  base64DecodeToExistingUint8Array(bufferView, 1844, "EhATFBUWFxgZGhscHR4fICEQECIQEBAjJCUmJygpECorEBAQEBAQEBAQEBAsLS4QLxAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEDAQEBAxEDIzNDU2NxAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBA4EBA5OhA7PD0QEBAQEBA+EBA/QEFCQ0RFRkdISUpLTBBNTk8QEBAQEBAQEBAQEBAQEBAQEBAQEBBQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBBRUhAQEFMQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQVBAQEBAQEBAQEBAQEBAQEBAQEBAQVVYQEBAQEBAQVxAQEBAQWFlaEBAQEBBbXBAQEBAQEBAQEF0QEBAQEBAQEBAQEBA=");
  base64DecodeToExistingUint8Array(bufferView, 2388, "//////////////////////////////////////////8AAAAAgEAABAAAAEABAAAAAAAAAAChkAE=");
  base64DecodeToExistingUint8Array(bufferView, 2474, "////////////////////////////////MASw");
  base64DecodeToExistingUint8Array(bufferView, 2532, "+AM=");
  base64DecodeToExistingUint8Array(bufferView, 2559, "ggAAAAAAAP7/////v7YAAAAAABAAPwD/FwAAAAAB+P//AAAB");
  base64DecodeToExistingUint8Array(bufferView, 2606, "wL//PQAAAIACAAAA////Bw==");
  base64DecodeToExistingUint8Array(bufferView, 2632, "wP8BAAAAAAAA+D8kAADA//8/AAAAAAAO");
  base64DecodeToExistingUint8Array(bufferView, 2670, "+P//////BwAAAAAAABT+If4ADAACAAIAAAAAAAAQHiAAAAwAAEAGAAAAAAAAEIY5AgAAACMABgAAAAAAABC+IQAADAAA/AIAAAAAAACQHiBgAAwAAAAEAAAAAAAAAAEgAAAAAAAAEQAAAAAAAMDBPWAADAAAAAIAAAAAAACQQDAAAAwAAAADAAAAAAAAGB4gAAAMAAAAAgAAAAAAAAAABFw=");
  base64DecodeToExistingUint8Array(bufferView, 2842, "8gfAfw==");
  base64DecodeToExistingUint8Array(bufferView, 2858, "8h9APw==");
  base64DecodeToExistingUint8Array(bufferView, 2871, "AwAAoAIAAAAAAAD+f9/g//7///8fQA==");
  base64DecodeToExistingUint8Array(bufferView, 2905, "4P1mAAAAwwEAHgBkIAAg");
  base64DecodeToExistingUint8Array(bufferView, 2931, "EA==");
  base64DecodeToExistingUint8Array(bufferView, 2943, "4A==");
  base64DecodeToExistingUint8Array(bufferView, 2966, "HAAAABwAAAAMAAAADAAAAAAAAACwP0D+jyAAAAAAAHgAAAAAAAAIAAAAAAAAAGAAAAAAAg==");
  base64DecodeToExistingUint8Array(bufferView, 3032, "hwEEDg==");
  base64DecodeToExistingUint8Array(bufferView, 3062, "gAkAAAAAAABAf+Uf+J8AAAAAgAD//wEAAAAAAAAADwAAAAAA0BcEAAAAAPgPAAMAAAA8OwAAAAAAAECjAwAAAAAAAPDPAAAAAAAAAAA/");
  base64DecodeToExistingUint8Array(bufferView, 3150, "9//9IRADAAAAAADw/////////wcAAQAAAPj///////////////s=");
  base64DecodeToExistingUint8Array(bufferView, 3211, "oAPgAOAA4ABgAPgAA5B8AAAAAAAA3/8CgAAA/x8AAAAAAAD/////AQ==");
  base64DecodeToExistingUint8Array(bufferView, 3267, "MA==");
  base64DecodeToExistingUint8Array(bufferView, 3281, "gAM=");
  base64DecodeToExistingUint8Array(bufferView, 3297, "gACA");
  base64DecodeToExistingUint8Array(bufferView, 3312, "/////wAAAAAAgA==");
  base64DecodeToExistingUint8Array(bufferView, 3348, "IAAAAAA8Pgg=");
  base64DecodeToExistingUint8Array(bufferView, 3367, "fg==");
  base64DecodeToExistingUint8Array(bufferView, 3379, "cAAAIA==");
  base64DecodeToExistingUint8Array(bufferView, 3443, "PwAQ");
  base64DecodeToExistingUint8Array(bufferView, 3457, "gPe/AAAA8A==");
  base64DecodeToExistingUint8Array(bufferView, 3474, "AwD/////Aw==");
  base64DecodeToExistingUint8Array(bufferView, 3490, "AQAABw==");
  base64DecodeToExistingUint8Array(bufferView, 3507, "A0QIAABgEA==");
  base64DecodeToExistingUint8Array(bufferView, 3532, "MAAAAP//A4AAAAAAwD8AAID/AwAAAAAABwAAAAAAyDMAgAAAYAAAAAAAAAAAfmYACBAAAAAAARAAAAAAAACdwQIAACAAMFg=");
  base64DecodeToExistingUint8Array(bufferView, 3615, "+AAO");
  base64DecodeToExistingUint8Array(bufferView, 3632, "ICEAAAAAAEA=");
  base64DecodeToExistingUint8Array(bufferView, 3658, "/P8DAAAAAAAAAP//CAD//wAAAAAk");
  base64DecodeToExistingUint8Array(bufferView, 3699, "gIBAAAQAAABAAQAAAAAAAQAAAADAAAAAAAAAAAAIAAAO");
  base64DecodeToExistingUint8Array(bufferView, 3763, "IA==");
  base64DecodeToExistingUint8Array(bufferView, 3792, "AQ==");
  base64DecodeToExistingUint8Array(bufferView, 3810, "wAc=");
  base64DecodeToExistingUint8Array(bufferView, 3828, "bvAAAAAAAIc=");
  base64DecodeToExistingUint8Array(bufferView, 3856, "YAAAAAAAAADw");
  base64DecodeToExistingUint8Array(bufferView, 3913, "GA==");
  base64DecodeToExistingUint8Array(bufferView, 3932, "wP8B");
  base64DecodeToExistingUint8Array(bufferView, 3956, "AgAAAAAAAP9/AAAAAAAAgAMAAAAAAHgmACAAAAAAAAAHAAAAgO8fAAAAAAAAAAgAAwAAAAAAwH8Ang==");
  base64DecodeToExistingUint8Array(bufferView, 4025, "gNNA");
  base64DecodeToExistingUint8Array(bufferView, 4047, "gPgHAAADAAAAAAAAGAEAAADAHx8=");
  base64DecodeToExistingUint8Array(bufferView, 4091, "/1wAAEA=");
  base64DecodeToExistingUint8Array(bufferView, 4106, "+IUN");
  base64DecodeToExistingUint8Array(bufferView, 4138, "PLABAAAw");
  base64DecodeToExistingUint8Array(bufferView, 4154, "+KcB");
  base64DecodeToExistingUint8Array(bufferView, 4169, "KL8=");
  base64DecodeToExistingUint8Array(bufferView, 4183, "4LwP");
  base64DecodeToExistingUint8Array(bufferView, 4217, "gP8G");
  base64DecodeToExistingUint8Array(bufferView, 4251, "WAg=");
  base64DecodeToExistingUint8Array(bufferView, 4270, "8AwBAAAA/gcAAAAA+HmAAH4OAAAAAAD8fwM=");
  base64DecodeToExistingUint8Array(bufferView, 4314, "f78=");
  base64DecodeToExistingUint8Array(bufferView, 4326, "/P///G0=");
  base64DecodeToExistingUint8Array(bufferView, 4346, "frS/");
  base64DecodeToExistingUint8Array(bufferView, 4358, "ow==");
  base64DecodeToExistingUint8Array(bufferView, 4402, "GAAAAAAAAAD/AQ==");
  base64DecodeToExistingUint8Array(bufferView, 4466, "HwAAAAAAAAB/AA8=");
  base64DecodeToExistingUint8Array(bufferView, 4509, "gAAAAAAAAACA//8AAAAAAAAAABs=");
  base64DecodeToExistingUint8Array(bufferView, 4551, "YA8=");
  base64DecodeToExistingUint8Array(bufferView, 4576, "gAP4/+cPAAAAPA==");
  base64DecodeToExistingUint8Array(bufferView, 4604, "HA==");
  base64DecodeToExistingUint8Array(bufferView, 4628, "////////f/j//////x8gABAAAPj+/w==");
  base64DecodeToExistingUint8Array(bufferView, 4660, "f///+dsH");
  base64DecodeToExistingUint8Array(bufferView, 4698, "/z8=");
  base64DecodeToExistingUint8Array(bufferView, 4753, "8A==");
  base64DecodeToExistingUint8Array(bufferView, 4782, "fw==");
  base64DecodeToExistingUint8Array(bufferView, 4796, "8A8=");
  base64DecodeToExistingUint8Array(bufferView, 4851, "+A==");
  base64DecodeToExistingUint8Array(bufferView, 4852, "EhMUFRYXEBAQEBAQEBAQEBgQEBkQEBAQEBAQEBobERwdHhAQHxAQEBAQEBAgIRAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECIjEBAQJBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAlEBAQJhAQEBAnEBAQEBAQECgQEBAQEBAQEBAQECkQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQKhAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQKywtLhAQEBAQEBAQEBAQEBAQEBAQLxAQEBAQEBAwEBAQEBAQEBAQEBAQEBA=");
  base64DecodeToExistingUint8Array(bufferView, 5396, "//////////////////////////////////////////8AAAAAAAAAAP7//wf+//8HAAAAAAAEIAT//3////9/////////////////////////////////9/D/////////////////////////////////7/////8BAwAAAB8=");
  base64DecodeToExistingUint8Array(bufferView, 5532, "IAAAAAAAz7xA1///+////////////7///////////////////////wP8///////////////////////////+////fwD//////wE=");
  base64DecodeToExistingUint8Array(bufferView, 5640, "/////78g///////n");
  base64DecodeToExistingUint8Array(bufferView, 5672, "/////////////z8/");
  base64DecodeToExistingUint8Array(bufferView, 5700, "/wH//////+cAAAAAAAAAAP///////////////////////////////wAAAAAAAAAA//8/P/////8/P/+q////P////////99f3B/PD/8f3B8=");
  base64DecodeToExistingUint8Array(bufferView, 5794, "AoAAAP8f");
  base64DecodeToExistingUint8Array(bufferView, 5812, "hPwvPlC9H/LgQwAA/////xg=");
  base64DecodeToExistingUint8Array(bufferView, 5866, "wP///////wMAAP//////f///////f/////////////////////8feAwA/////78g");
  base64DecodeToExistingUint8Array(bufferView, 5948, "//////8/AAD///8/");
  base64DecodeToExistingUint8Array(bufferView, 5976, "/P///////////////3j////////8BwAAAABgBwAAAAAAAP//////9/8B/////////////wAAAAAAAAAAfwD4");
  base64DecodeToExistingUint8Array(bufferView, 6072, "/v//B/7//wc=");
  base64DecodeToExistingUint8Array(bufferView, 6100, "/////////////w==");
  base64DecodeToExistingUint8Array(bufferView, 6122, "/////w//////Dw==");
  base64DecodeToExistingUint8Array(bufferView, 6148, "////////BwD///////8H");
  base64DecodeToExistingUint8Array(bufferView, 6184, "//////////8=");
  base64DecodeToExistingUint8Array(bufferView, 6204, "//////////8=");
  base64DecodeToExistingUint8Array(bufferView, 6228, "/////////////9///////////99k3v/r7/////////+/59/f////e1/8/f//////////////////////////////////////////////////////P/////3///f////3///f////3///f////3/////9/////f//9w8AAAAAAAD//////////w8=");
  base64DecodeToExistingUint8Array(bufferView, 6394, "////A////wP///8D");
  base64DecodeToExistingUint8Array(bufferView, 6420, "BwgJCgsMBgYGBgYGBgYGBg0GBg4GBgYGBgYGBg8QERIGEwYGBgYGBgYGBgYUFQYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBhYXBgYGGAYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGGQYGBgYaBgYGBgYGBhsGBgYGBgYGBgYGBhwGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGHQYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGHgYGBgYGBgYGBgYGBgYGBgYGBgYGBgY=");
  base64DecodeToExistingUint8Array(bufferView, 7043, "JCsrKysrKysrAQBUVlZWVlZWVlY=");
  base64DecodeToExistingUint8Array(bufferView, 7082, "GAAAACsrKysrKysHKytbVlZWVlZWVkpWVgUxUDFQMVAxUDFQMVAxUDFQJFB5MVAxUDE4UDFQMVAxUDFQMVAxUDFQTjECTg0NTgNOACRuAE4xJm5RTiRQTjkUgRsdHVMxUDFQDTFQMVAxUBtTJFAxAlx7XHtce1x7XHsUeVx7XHtcLStJA0gDeFx7FACWCgErKAYGACoGKiorB7u1Kx4AKwcrKysBKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysBKysrKysrKysrKysrKysrKysrKysrKysqKysrKysrKysrKysrK81GzSsAJSsHAQYBVVZWVlZWVVZWAiSBgYGBgRWBgYEAACsAstGy0bLRstEAAM3MAQDX19fX14OBgYGBgYGBgYGBrKysrKysrKysrBwAAAAAADFQMVAxUDFQMVAxAgAAMVAxUDFQMVAxUDFQMVAxUDFQTjFQMVBOMVAxUDFQMVAxUDFQMVAxAoemh6aHpoemh6aHpoemh6YqKysrKysrKysrKysrAAAAVFZWVlZWVlZWVlZWVg==");
  base64DecodeToExistingUint8Array(bufferView, 7591, "VFZWVlZWVlZWVlZWVgwADCorKysrKysrKysrKysrByoB");
  base64DecodeToExistingUint8Array(bufferView, 7677, "KisrKysrKysrKysrKysrKysrKysrKysrKysrVlZsgRUAKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrB2wDQSsrVlZWVlZWVlZWVlZWVlYsVisrKysrKysrKysrKysrKysrKysrKwE=");
  base64DecodeToExistingUint8Array(bufferView, 7836, "DGwAAAAAAAY=");
  base64DecodeToExistingUint8Array(bufferView, 7882, "BiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiVWep4mBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBgErK09WViwrf1ZWOSsrVVZWKytPVlYsK39WVoE3dVt7XCsrT1ZWAqwEAAA5KytVVlYrK09WViwrK1ZWMhOBVwBvgX7J134tgYEOfjl/b1cAgYF+FQB+AysrKysrKysrKysrKwcrJCuXKysrKysrKysrKisrKysrVlZWVlaAgYGBgTm7KisrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysBgYGBgYGBgYGBgYGBgYGByaysrKysrKysrKysrKysrNANAE4xArTBwdfXJFAxUDFQMVAxUDFQMVAxUDFQMVAxUDFQMVAxUDFQMVAxUNfXU8FH1NfX1wUrKysrKysrKysrKysHAQAB");
  base64DecodeToExistingUint8Array(bufferView, 8333, "TjFQMVAxUDFQMVAxUDFQDQAAAAAAJFAxUDFQMVAxUA==");
  base64DecodeToExistingUint8Array(bufferView, 8398, "KysrKysrKysrKyt5XHtce097XHtce1x7XHtce1x7XHtce1x7XC0rK3kUXHtcLXkqXCdce1x7XHukAAq0XHtce08DeDgrKysrKysrKysrKysrTy0rKwE=");
  base64DecodeToExistingUint8Array(bufferView, 8511, "SA==");
  base64DecodeToExistingUint8Array(bufferView, 8521, "KisrKysrKysrKysrKysrKysrKysrKysrKysr");
  base64DecodeToExistingUint8Array(bufferView, 8581, "KysrKysrKysHAEhWVlZWVlZWVgI=");
  base64DecodeToExistingUint8Array(bufferView, 8656, "KysrKysrKysrKysrK1VWVlZWVlZWVlZWVlYO");
  base64DecodeToExistingUint8Array(bufferView, 8714, "JCsrKysrKysrKysrBwBWVlZWVlZWVlZWVlY=");
  base64DecodeToExistingUint8Array(bufferView, 8784, "JCsrKysrKysrKysrKysrKysHAAAAAFZWVlZWVlZWVlZWVlZWVlZW");
  base64DecodeToExistingUint8Array(bufferView, 8881, "KisrKysrKysrKytWVlZWVlZWVlZWDg==");
  base64DecodeToExistingUint8Array(bufferView, 8935, "KisrKysrKysrKytWVlZWVlZWVlZWDg==");
  base64DecodeToExistingUint8Array(bufferView, 9000, "KysrKysrKysrKytVVlZWVlZWVlZWVg4=");
  base64DecodeToExistingUint8Array(bufferView, 9089, "CAAAVgEAADk=");
  base64DecodeToExistingUint8Array(bufferView, 9104, "ASAAAADg//8Avx0AAOcCAAB5AAACJAAAAQEAAAD///8AAAAAAQIAAAD+//8BOf//ABj//wGH//8A1P7/AMMAAAHSAAABzgAAAc0AAAFPAAABygAAAcsAAAHPAAAAYQAAAdMAAAHRAAAAowAAAdUAAACCAAAB1gAAAdoAAAHZAAAB2wAAADgAAAMAAAAAsf//AZ///wHI//8CKCQAAAAAAAEBAAAA////ADP//wAm//8Bfv//ASsqAAFd//8BKCoAAD8qAAE9//8BRQAAAUcAAAAfKgAAHCoAAB4qAAAu//8AMv//ADb//wA1//8AT6UAAEulAAAx//8AKKUAAESlAAAv//8ALf//APcpAABBpQAA/SkAACv//wAq//8A5ykAAEOlAAAqpQAAu///ACf//wC5//8AJf//ABWlAAASpQACJEwAAAAAAAEgAAAA4P//AQEAAAD///8AVAAAAXQAAAEmAAABJQAAAUAAAAE/AAAA2v//ANv//wDh//8AwP//AMH//wEIAAAAwv//AMf//wDR//8Ayv//APj//wCq//8AsP//AAcAAACM//8BxP//AKD//wH5//8CGnAAAQEAAAD///8BIAAAAOD//wFQAAABDwAAAPH//wAAAAABMAAAAND//wEBAAAA////AAAAAADACwABYBwAAAAAAAHQlwABCAAAAPj//wIFigAAAAAAAUD0/wCe5/8AwokAANvn/wCS5/8Ak+f/AJzn/wCd5/8ApOf/AAAAAAA4igAABIoAAOYOAAEBAAAA////AAAAAADF//8BQeL/Ah2PAAAIAAAB+P//AAAAAABWAAABqv//AEoAAABkAAAAgAAAAHAAAAB+AAAACQAAAbb//wH3//8A2+P/AZz//wGQ//8BgP//AYL//wIFrAAAAAAAARAAAADw//8BHAAAAQEAAAGj4v8BQd//Abrf/wDk//8CC7EAAQEAAAD///8BMAAAAND//wAAAAABCdb/ARrx/wEZ1v8A1dX/ANjV/wHk1f8BA9b/AeHV/wHi1f8BwdX/AAAAAACg4/8AAAAAAQEAAAD///8CDLwAAAAAAAEBAAAA////Abxa/wGgAwAB/HX/Adha/wAwAAABsVr/AbVa/wG/Wv8B7lr/AdZa/wHrWv8B0P//Ab1a/wHIdf8AAAAAADBo/wBg/P8AAAAAASAAAADg//8AAAAAASgAAADY//8AAAAAAUAAAADA//8AAAAAASAAAADg//8AAAAAASAAAADg//8AAAAAASIAAADe//8=");
  base64DecodeToExistingUint8Array(bufferView, 10061, "BidRb3c=");
  base64DecodeToExistingUint8Array(bufferView, 10076, "fAAAfwAAAAAAAAAAg46SlwCq");
  base64DecodeToExistingUint8Array(bufferView, 10104, "tMQ=");
  base64DecodeToExistingUint8Array(bufferView, 10226, "xskAAADb");
  base64DecodeToExistingUint8Array(bufferView, 10315, "3gAAAADhAAAAAAAAAOQ=");
  base64DecodeToExistingUint8Array(bufferView, 10340, "5w==");
  base64DecodeToExistingUint8Array(bufferView, 10426, "6g==");
  base64DecodeToExistingUint8Array(bufferView, 10549, "7Q==");
  base64DecodeToExistingUint8Array(bufferView, 10572, "MAwxDXgOfw+AEIERhhKJE4oTjhSPFZAWkxOUF5UYlhmXGpobnBmdHJ4dnx6mH6kfrh+xILIgtyG/IsUjyCPLI90k8iP2JfcmIC06Lj0vPjA/MUAxQzJEM0U0UDVRNlI3UzhUOVk6WztcPGE9Yz5lP2ZAaEFpQmpAa0NsRG9CcUVyRnVHfUiCSYdKiUuKTItMjE2STp1PnlBFV3sdfB19HX9YhlmIWolailqMW45cj1ysXa1erl6vXsJfzGDNYc5hz2LQY9Fk1WXWZtdn8GjxafJq82v0bPVt+W79Lf4t/y1QaVFpUmlTaVRpVWlWaVdpWGlZaVppW2lcaV1pXmlfaYIAgwCEAIUAhgCHAIgAiQDAdc92gImBioKLhYyGjXCdcZ12nneeeJ95n3qge6B8oX2hs6K6o7ujvKS+pcOizKTaptum5Wrqp+un7G7zovio+aj6qfup/KQmsCqxK7JOs4QIYrpju2S8Zb1mvm2/bsBvwXDCfsN/w33PjdCU0avSrNOt1LDVsday18TYxdnG2g==");
  base64DecodeToExistingUint8Array(bufferView, 10972, "PA==");
  base64DecodeToExistingUint8Array(bufferView, 10984, "AgAAACQAAABJAG4AZABlAHgAIABvAHUAdAAgAG8AZgAgAHIAYQBuAGcAZQ==");
  base64DecodeToExistingUint8Array(bufferView, 11036, "LA==");
  base64DecodeToExistingUint8Array(bufferView, 11048, "AgAAABoAAAB+AGwAaQBiAC8AYQByAHIAYQB5AC4AdABz");
  base64DecodeToExistingUint8Array(bufferView, 11084, "fA==");
  base64DecodeToExistingUint8Array(bufferView, 11096, "AgAAAF4AAABFAGwAZQBtAGUAbgB0ACAAdAB5AHAAZQAgAG0AdQBzAHQAIABiAGUAIABuAHUAbABsAGEAYgBsAGUAIABpAGYAIABhAHIAcgBhAHkAIABpAHMAIABoAG8AbABlAHk=");
  base64DecodeToExistingUint8Array(bufferView, 11212, "LA==");
  base64DecodeToExistingUint8Array(bufferView, 11224, "AgAAABwAAABJAG4AdgBhAGwAaQBkACAAbABlAG4AZwB0AGg=");
  base64DecodeToExistingUint8Array(bufferView, 11260, "PA==");
  base64DecodeToExistingUint8Array(bufferView, 11272, "AgAAACYAAAB+AGwAaQBiAC8AYQByAHIAYQB5AGIAdQBmAGYAZQByAC4AdABz");
  base64DecodeToExistingUint8Array(bufferView, 11324, "PA==");
  base64DecodeToExistingUint8Array(bufferView, 11336, "AgAAACYAAAB+AGwAaQBiAC8AcwB0AGEAdABpAGMAYQByAHIAYQB5AC4AdABz");
  base64DecodeToExistingUint8Array(bufferView, 11388, "PA==");
  base64DecodeToExistingUint8Array(bufferView, 11400, "AgAAACQAAAB+AGwAaQBiAC8AdAB5AHAAZQBkAGEAcgByAGEAeQAuAHQAcw==");
  base64DecodeToExistingUint8Array(bufferView, 11452, "PA==");
  base64DecodeToExistingUint8Array(bufferView, 11464, "AgAAACoAAABPAGIAagBlAGMAdAAgAGEAbAByAGUAYQBkAHkAIABwAGkAbgBuAGUAZA==");
  base64DecodeToExistingUint8Array(bufferView, 11548, "PA==");
  base64DecodeToExistingUint8Array(bufferView, 11560, "AgAAACgAAABPAGIAagBlAGMAdAAgAGkAcwAgAG4AbwB0ACAAcABpAG4AbgBlAGQ=");
  base64DecodeToExistingUint8Array(bufferView, 11648, "CAAAACAAAAAgAAAAIAAAAAAAAABCAAAAAkEAAEEAAABk");
}
function wasm2js_trap() { throw new Error('abort'); }

  function wasm2js_memory_fill(dest, value, size) {
    dest = dest >>> 0;
    size = size >>> 0;
    if (dest + size > bufferView.length) throw "trap: invalid memory.fill";
    bufferView.fill(value, dest, dest + size);
  }
      
  function wasm2js_memory_copy(dest, source, size) {
    // TODO: traps on invalid things
    bufferView.copyWithin(dest, source, source + size);
  }
      
function asmFunc(imports) {
 var buffer = new ArrayBuffer(65536);
 var HEAP8 = new Int8Array(buffer);
 var HEAP16 = new Int16Array(buffer);
 var HEAP32 = new Int32Array(buffer);
 var HEAPU8 = new Uint8Array(buffer);
 var HEAPU16 = new Uint16Array(buffer);
 var HEAPU32 = new Uint32Array(buffer);
 var HEAPF32 = new Float32Array(buffer);
 var HEAPF64 = new Float64Array(buffer);
 var Math_imul = Math.imul;
 var Math_fround = Math.fround;
 var Math_abs = Math.abs;
 var Math_clz32 = Math.clz32;
 var Math_min = Math.min;
 var Math_max = Math.max;
 var Math_floor = Math.floor;
 var Math_ceil = Math.ceil;
 var Math_trunc = Math.trunc;
 var Math_sqrt = Math.sqrt;
 var env = imports.env;
 var fimport$0 = env.abort;
 var global$0 = 0;
 var global$1 = 0;
 var global$2 = 0;
 var global$3 = 0;
 var global$4 = 0;
 var global$5 = 0;
 var global$6 = 11648;
 function $0($0_1) {
  $0_1 = $0_1 | 0;
  if (!$0_1) {
   return
  }
  $0_1 = $0_1 - 20 | 0;
  if (($6($0_1 | 0) | 0 | 0) == (global$2 | 0)) {
   $15($0_1 | 0);
   $9($0_1 | 0, global$5 | 0, !global$2 | 0);
  }
 }
 
 function $1($0_1, $1_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  return HEAPU8[($0_1 + $1_1 | 0) >> 0] | 0 | 0;
 }
 
 function $2($0_1) {
  $0_1 = $0_1 | 0;
  return (HEAP32[($0_1 + 4 | 0) >> 2] | 0) & -4 | 0 | 0;
 }
 
 function $3($0_1) {
  $0_1 = $0_1 | 0;
  return (HEAP32[(($0_1 - 20 | 0) + 16 | 0) >> 2] | 0) >>> 1 | 0 | 0;
 }
 
 function $4($0_1, $1_1, $2_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  $2_1 = $2_1 | 0;
  HEAP8[($0_1 + $1_1 | 0) >> 0] = $2_1;
 }
 
 function $5($0_1, $1_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  var $2_1 = 0;
  if ($0_1 >>> 0 > 1073741804 >>> 0) {
   fimport$0(1648 | 0, 1712 | 0, 125 | 0, 30 | 0);
   wasm2js_trap();
  }
  if (!global$0) {
   $12()
  }
  $2_1 = $25(global$0 | 0, $0_1 + 16 | 0 | 0) | 0;
  HEAP32[($2_1 + 12 | 0) >> 2] = $1_1;
  HEAP32[($2_1 + 16 | 0) >> 2] = $0_1;
  $9($2_1 | 0, global$1 | 0, global$2 | 0);
  global$3 = ($10($2_1 | 0) | 0) + global$3 | 0;
  return $2_1 + 20 | 0 | 0;
 }
 
 function $6($0_1) {
  $0_1 = $0_1 | 0;
  return (HEAP32[($0_1 + 4 | 0) >> 2] | 0) & 3 | 0 | 0;
 }
 
 function $7($0_1, $1_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  return ((HEAPU8[(($0_1 + ((HEAPU8[($0_1 + ($1_1 >>> 8 | 0) | 0) >> 0] | 0) << 5 | 0) | 0) + (($1_1 & 255 | 0) >>> 3 | 0) | 0) >> 0] | 0) >>> ($1_1 & 7 | 0) | 0) & 1 | 0 | 0;
 }
 
 function $8($0_1, $1_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  var $3_1 = 0, $4_1 = 0, $5_1 = 0, $2_1 = 0, $29_1 = 0, $41 = 0, wasm2js_i32$0 = 0, wasm2js_i32$1 = 0;
  $3_1 = (HEAP32[$1_1 >> 2] | 0) & -4 | 0;
  if ($3_1 >>> 0 < 256 >>> 0) {
   $29_1 = $3_1 >>> 4 | 0
  } else {
   $3_1 = $3_1 >>> 0 >= 1073741820 >>> 0 ? 1073741820 : $3_1;
   $4_1 = 31 - Math_clz32($3_1) | 0;
   $2_1 = $4_1 - 7 | 0;
   $29_1 = ($3_1 >>> ($4_1 - 4 | 0) | 0) ^ 16 | 0;
  }
  $4_1 = $29_1;
  $5_1 = HEAP32[($1_1 + 8 | 0) >> 2] | 0;
  $3_1 = HEAP32[($1_1 + 4 | 0) >> 2] | 0;
  if ($3_1) {
   HEAP32[($3_1 + 8 | 0) >> 2] = $5_1
  }
  if ($5_1) {
   HEAP32[($5_1 + 4 | 0) >> 2] = $3_1
  }
  $41 = $1_1;
  $1_1 = $0_1 + ((($2_1 << 4 | 0) + $4_1 | 0) << 2 | 0) | 0;
  if (($41 | 0) == (HEAP32[($1_1 + 96 | 0) >> 2] | 0 | 0)) {
   HEAP32[($1_1 + 96 | 0) >> 2] = $5_1;
   if (!$5_1) {
    $1_1 = $0_1 + ($2_1 << 2 | 0) | 0;
    $3_1 = (HEAP32[($1_1 + 4 | 0) >> 2] | 0) & (__wasm_rotl_i32(-2 | 0, $4_1 | 0) | 0) | 0;
    HEAP32[($1_1 + 4 | 0) >> 2] = $3_1;
    if (!$3_1) {
     (wasm2js_i32$0 = $0_1, wasm2js_i32$1 = (HEAP32[$0_1 >> 2] | 0) & (__wasm_rotl_i32(-2 | 0, $2_1 | 0) | 0) | 0), HEAP32[wasm2js_i32$0 >> 2] = wasm2js_i32$1
    }
   }
  }
 }
 
 function $9($0_1, $1_1, $2_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  $2_1 = $2_1 | 0;
  var $3_1 = 0;
  $3_1 = HEAP32[($1_1 + 8 | 0) >> 2] | 0;
  HEAP32[($0_1 + 4 | 0) >> 2] = $1_1 | $2_1 | 0;
  HEAP32[($0_1 + 8 | 0) >> 2] = $3_1;
  $16($3_1 | 0, $0_1 | 0);
  HEAP32[($1_1 + 8 | 0) >> 2] = $0_1;
 }
 
 function $10($0_1) {
  $0_1 = $0_1 | 0;
  return ((HEAP32[$0_1 >> 2] | 0) & -4 | 0) + 4 | 0 | 0;
 }
 
 function $11($0_1, $1_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  var $2_1 = 0, $3_1 = 0, $4_1 = 0, $5_1 = 0, $81 = 0, $6_1 = 0, $58 = 0;
  $3_1 = HEAP32[$1_1 >> 2] | 0;
  $4_1 = ($1_1 + 4 | 0) + ((HEAP32[$1_1 >> 2] | 0) & -4 | 0) | 0;
  $2_1 = HEAP32[$4_1 >> 2] | 0;
  if ($2_1 & 1 | 0) {
   $8($0_1 | 0, $4_1 | 0);
   $3_1 = ($3_1 + 4 | 0) + ($2_1 & -4 | 0) | 0;
   HEAP32[$1_1 >> 2] = $3_1;
   $4_1 = ($1_1 + 4 | 0) + ((HEAP32[$1_1 >> 2] | 0) & -4 | 0) | 0;
   $2_1 = HEAP32[$4_1 >> 2] | 0;
  }
  if ($3_1 & 2 | 0) {
   $1_1 = HEAP32[($1_1 - 4 | 0) >> 2] | 0;
   $6_1 = HEAP32[$1_1 >> 2] | 0;
   $8($0_1 | 0, $1_1 | 0);
   $3_1 = ($6_1 + 4 | 0) + ($3_1 & -4 | 0) | 0;
   HEAP32[$1_1 >> 2] = $3_1;
  }
  HEAP32[$4_1 >> 2] = $2_1 | 2 | 0;
  HEAP32[($4_1 - 4 | 0) >> 2] = $1_1;
  $58 = $0_1;
  $2_1 = $3_1 & -4 | 0;
  if ($2_1 >>> 0 < 256 >>> 0) {
   $81 = $2_1 >>> 4 | 0
  } else {
   $2_1 = $2_1 >>> 0 >= 1073741820 >>> 0 ? 1073741820 : $2_1;
   $3_1 = 31 - Math_clz32($2_1) | 0;
   $5_1 = $3_1 - 7 | 0;
   $81 = ($2_1 >>> ($3_1 - 4 | 0) | 0) ^ 16 | 0;
  }
  $2_1 = $81;
  $3_1 = HEAP32[(($58 + (($2_1 + ($5_1 << 4 | 0) | 0) << 2 | 0) | 0) + 96 | 0) >> 2] | 0;
  HEAP32[($1_1 + 4 | 0) >> 2] = 0;
  HEAP32[($1_1 + 8 | 0) >> 2] = $3_1;
  if ($3_1) {
   HEAP32[($3_1 + 4 | 0) >> 2] = $1_1
  }
  HEAP32[(($0_1 + ((($5_1 << 4 | 0) + $2_1 | 0) << 2 | 0) | 0) + 96 | 0) >> 2] = $1_1;
  HEAP32[$0_1 >> 2] = HEAP32[$0_1 >> 2] | 0 | (1 << $5_1 | 0) | 0;
  $0_1 = $0_1 + ($5_1 << 2 | 0) | 0;
  HEAP32[($0_1 + 4 | 0) >> 2] = HEAP32[($0_1 + 4 | 0) >> 2] | 0 | (1 << $2_1 | 0) | 0;
 }
 
 function $12() {
  var $0_1 = 0, i64toi32_i32$1 = 0, i64toi32_i32$4 = 0, $1_1 = 0, i64toi32_i32$2 = 0, $9_1 = 0, i64toi32_i32$3 = 0, $8_1 = 0, i64toi32_i32$0 = 0;
  $0_1 = __wasm_memory_size();
  if (($0_1 | 0) <= (0 | 0)) {
   $9_1 = (__wasm_memory_grow(1 - $0_1 | 0 | 0) | 0) < (0 | 0)
  } else {
   $9_1 = 0
  }
  if ($9_1) {
   wasm2js_trap()
  }
  HEAP32[11696 >> 2] = 0;
  HEAP32[13264 >> 2] = 0;
  label1 : while (1) {
   if ($1_1 >>> 0 < 23 >>> 0) {
    HEAP32[((($1_1 << 2 | 0) + 11696 | 0) + 4 | 0) >> 2] = 0;
    $0_1 = 0;
    label : while (1) {
     if ($0_1 >>> 0 < 16 >>> 0) {
      HEAP32[((((($1_1 << 4 | 0) + $0_1 | 0) << 2 | 0) + 11696 | 0) + 96 | 0) >> 2] = 0;
      $0_1 = $0_1 + 1 | 0;
      continue label;
     }
     break label;
    };
    $1_1 = $1_1 + 1 | 0;
    continue label1;
   }
   break label1;
  };
  i64toi32_i32$1 = __wasm_memory_size();
  i64toi32_i32$0 = i64toi32_i32$1 >> 31 | 0;
  i64toi32_i32$2 = i64toi32_i32$1;
  i64toi32_i32$1 = 0;
  i64toi32_i32$3 = 16;
  i64toi32_i32$4 = i64toi32_i32$3 & 31 | 0;
  if (32 >>> 0 <= (i64toi32_i32$3 & 63 | 0) >>> 0) {
   i64toi32_i32$1 = i64toi32_i32$2 << i64toi32_i32$4 | 0;
   $8_1 = 0;
  } else {
   i64toi32_i32$1 = ((1 << i64toi32_i32$4 | 0) - 1 | 0) & (i64toi32_i32$2 >>> (32 - i64toi32_i32$4 | 0) | 0) | 0 | (i64toi32_i32$0 << i64toi32_i32$4 | 0) | 0;
   $8_1 = i64toi32_i32$2 << i64toi32_i32$4 | 0;
  }
  $26(11696 | 0, 13268 | 0, $8_1 | 0, i64toi32_i32$1 | 0);
  global$0 = 11696;
 }
 
 function $13($0_1) {
  $0_1 = $0_1 | 0;
  var $1_1 = 0, $11_1 = 0;
  $1_1 = $0_1 - 4 | 0;
  if ($0_1 ? $0_1 & 15 | 0 : 1) {
   $11_1 = 1
  } else {
   $11_1 = (HEAP32[$1_1 >> 2] | 0) & 1 | 0
  }
  return $1_1 | 0;
 }
 
 function $14($0_1) {
  $0_1 = $0_1 | 0;
  HEAP32[($0_1 + 4 | 0) >> 2] = $0_1;
  HEAP32[($0_1 + 8 | 0) >> 2] = $0_1;
  return $0_1 | 0;
 }
 
 function $15($0_1) {
  $0_1 = $0_1 | 0;
  var $1_1 = 0;
  $1_1 = $2($0_1 | 0) | 0;
  if (!$1_1) {
   HEAP32[($0_1 + 8 | 0) >> 2] | 0;
   return;
  }
  $0_1 = HEAP32[($0_1 + 8 | 0) >> 2] | 0;
  HEAP32[($1_1 + 8 | 0) >> 2] = $0_1;
  $16($0_1 | 0, $1_1 | 0);
 }
 
 function $16($0_1, $1_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  HEAP32[($0_1 + 4 | 0) >> 2] = $1_1 | ((HEAP32[($0_1 + 4 | 0) >> 2] | 0) & 3 | 0) | 0;
 }
 
 function $17($0_1, $1_1, $2_1, $3_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  $2_1 = $2_1 | 0;
  $3_1 = $3_1 | 0;
  var $4_1 = 0;
  $1_1 = $0_1 + ($1_1 << 1 | 0) | 0;
  label : while (1) {
   $0_1 = $3_1;
   $3_1 = $0_1 - 1 | 0;
   if ($0_1) {
    $0_1 = HEAPU16[$1_1 >> 1] | 0;
    $4_1 = HEAPU16[$2_1 >> 1] | 0;
    if (($0_1 | 0) != ($4_1 | 0)) {
     return $0_1 - $4_1 | 0 | 0
    }
    $1_1 = $1_1 + 2 | 0;
    $2_1 = $2_1 + 2 | 0;
    continue label;
   }
   break label;
  };
  return 0 | 0;
 }
 
 function $18($0_1) {
  $0_1 = $0_1 | 0;
  var $1_1 = 0, $2_1 = 0;
  $1_1 = $5(12 | 0, 6 | 0) | 0;
  if (!$1_1) {
   $1_1 = $5(12 | 0, 3 | 0) | 0
  }
  HEAP32[$1_1 >> 2] = 0;
  HEAP32[($1_1 + 4 | 0) >> 2] = 0;
  HEAP32[($1_1 + 8 | 0) >> 2] = 0;
  if ($0_1 >>> 0 > 1073741820 >>> 0) {
   fimport$0(11232 | 0, 11280 | 0, 19 | 0, 57 | 0);
   wasm2js_trap();
  }
  $2_1 = $5($0_1 | 0, 1 | 0) | 0;
  wasm2js_memory_fill($2_1, 0, $0_1);
  HEAP32[$1_1 >> 2] = $2_1;
  HEAP32[($1_1 + 4 | 0) >> 2] = $2_1;
  HEAP32[($1_1 + 8 | 0) >> 2] = $0_1;
  return $1_1 | 0;
 }
 
 function $19($0_1, $1_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  var $2_1 = 0, $22_1 = 0, $3_1 = 0, $66 = 0, $50 = 0, $64 = 0;
  if ($1_1 >>> 0 < 256 >>> 0) {
   $22_1 = $1_1 >>> 4 | 0
  } else {
   $1_1 = $20($1_1 | 0) | 0;
   $3_1 = 31 - Math_clz32($1_1) | 0;
   $2_1 = $3_1 - 7 | 0;
   $22_1 = ($1_1 >>> ($3_1 - 4 | 0) | 0) ^ 16 | 0;
  }
  $1_1 = $22_1;
  $1_1 = (HEAP32[(($0_1 + ($2_1 << 2 | 0) | 0) + 4 | 0) >> 2] | 0) & (-1 << $1_1 | 0) | 0;
  if ($1_1) {
   $66 = HEAP32[(($0_1 + (((__wasm_ctz_i32($1_1 | 0) | 0) + ($2_1 << 4 | 0) | 0) << 2 | 0) | 0) + 96 | 0) >> 2] | 0
  } else {
   $1_1 = (HEAP32[$0_1 >> 2] | 0) & (-1 << ($2_1 + 1 | 0) | 0) | 0;
   if ($1_1) {
    $50 = $0_1;
    $0_1 = __wasm_ctz_i32($1_1 | 0) | 0;
    $64 = HEAP32[(($50 + (((__wasm_ctz_i32(HEAP32[(($50 + ($0_1 << 2 | 0) | 0) + 4 | 0) >> 2] | 0 | 0) | 0) + ($0_1 << 4 | 0) | 0) << 2 | 0) | 0) + 96 | 0) >> 2] | 0;
   } else {
    $64 = 0
   }
   $66 = $64;
  }
  return $66 | 0;
 }
 
 function $20($0_1) {
  $0_1 = $0_1 | 0;
  return ($0_1 >>> 0 < 536870910 >>> 0 ? ($0_1 + (1 << (27 - Math_clz32($0_1) | 0) | 0) | 0) - 1 | 0 : $0_1) | 0;
 }
 
 function $21($0_1) {
  $0_1 = $0_1 | 0;
  if ($0_1 >>> 0 > 1073741820 >>> 0) {
   fimport$0(1648 | 0, 1776 | 0, 461 | 0, 29 | 0);
   wasm2js_trap();
  }
  return ($0_1 >>> 0 <= 12 >>> 0 ? 12 : (($0_1 + 19 | 0) & -16 | 0) - 4 | 0) | 0;
 }
 
 function $22($0_1, $1_1, $2_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  $2_1 = $2_1 | 0;
  var $3_1 = 0, $4_1 = 0;
  $3_1 = HEAP32[$1_1 >> 2] | 0;
  $4_1 = ($3_1 & -4 | 0) - $2_1 | 0;
  if ($4_1 >>> 0 >= 16 >>> 0) {
   HEAP32[$1_1 >> 2] = $2_1 | ($3_1 & 2 | 0) | 0;
   $1_1 = ($1_1 + 4 | 0) + $2_1 | 0;
   HEAP32[$1_1 >> 2] = $4_1 - 4 | 0 | 1 | 0;
   $11($0_1 | 0, $1_1 | 0);
  } else {
   HEAP32[$1_1 >> 2] = $3_1 & -2 | 0;
   $0_1 = ($1_1 + 4 | 0) + ((HEAP32[$1_1 >> 2] | 0) & -4 | 0) | 0;
   HEAP32[$0_1 >> 2] = (HEAP32[$0_1 >> 2] | 0) & -3 | 0;
  }
 }
 
 function $23($0_1, $1_1, $2_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  $2_1 = $2_1 | 0;
  $2_1 = $25($0_1 | 0, $2_1 | 0) | 0;
  wasm2js_memory_copy($2_1 + 4 | 0, $1_1 + 4 | 0, (HEAP32[$1_1 >> 2] | 0) & -4 | 0);
  if ($1_1 >>> 0 >= 11684 >>> 0) {
   $24($0_1 | 0, $1_1 | 0)
  }
  return $2_1 | 0;
 }
 
 function $24($0_1, $1_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  HEAP32[$1_1 >> 2] = HEAP32[$1_1 >> 2] | 0 | 1 | 0;
  $11($0_1 | 0, $1_1 | 0);
 }
 
 function $25($0_1, $1_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  var $2_1 = 0, i64toi32_i32$1 = 0, i64toi32_i32$4 = 0, $3_1 = 0, i64toi32_i32$2 = 0, i64toi32_i32$3 = 0, $11_1 = 0, $40 = 0, $42 = 0, i64toi32_i32$0 = 0, wasm2js_i32$0 = 0, wasm2js_i32$1 = 0, wasm2js_i32$2 = 0;
  $2_1 = $21($1_1 | 0) | 0;
  $1_1 = $19($0_1 | 0, $2_1 | 0) | 0;
  if (!$1_1) {
   $1_1 = __wasm_memory_size();
   $3_1 = ((((4 << ((HEAP32[($0_1 + 1568 | 0) >> 2] | 0 | 0) != (($1_1 << 16 | 0) - 4 | 0 | 0)) | 0) + (wasm2js_i32$0 = $20($2_1 | 0) | 0, wasm2js_i32$1 = $2_1, wasm2js_i32$2 = $2_1 >>> 0 >= 256 >>> 0, wasm2js_i32$2 ? wasm2js_i32$0 : wasm2js_i32$1) | 0) + 65535 | 0) & -65536 | 0) >>> 16 | 0;
   if ((__wasm_memory_grow((($1_1 | 0) > ($3_1 | 0) ? $1_1 : $3_1) | 0) | 0) < (0 | 0)) {
    if ((__wasm_memory_grow($3_1 | 0) | 0) < (0 | 0)) {
     wasm2js_trap()
    }
   }
   $40 = $0_1;
   $42 = $1_1 << 16 | 0;
   i64toi32_i32$1 = __wasm_memory_size();
   i64toi32_i32$0 = i64toi32_i32$1 >> 31 | 0;
   i64toi32_i32$2 = i64toi32_i32$1;
   i64toi32_i32$1 = 0;
   i64toi32_i32$3 = 16;
   i64toi32_i32$4 = i64toi32_i32$3 & 31 | 0;
   if (32 >>> 0 <= (i64toi32_i32$3 & 63 | 0) >>> 0) {
    i64toi32_i32$1 = i64toi32_i32$2 << i64toi32_i32$4 | 0;
    $11_1 = 0;
   } else {
    i64toi32_i32$1 = ((1 << i64toi32_i32$4 | 0) - 1 | 0) & (i64toi32_i32$2 >>> (32 - i64toi32_i32$4 | 0) | 0) | 0 | (i64toi32_i32$0 << i64toi32_i32$4 | 0) | 0;
    $11_1 = i64toi32_i32$2 << i64toi32_i32$4 | 0;
   }
   $26($40 | 0, $42 | 0, $11_1 | 0, i64toi32_i32$1 | 0);
   $1_1 = $19($0_1 | 0, $2_1 | 0) | 0;
  }
  HEAP32[$1_1 >> 2] | 0;
  $8($0_1 | 0, $1_1 | 0);
  $22($0_1 | 0, $1_1 | 0, $2_1 | 0);
  return $1_1 | 0;
 }
 
 function $26($0_1, $1_1, $2_1, $2$hi) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  $2_1 = $2_1 | 0;
  $2$hi = $2$hi | 0;
  var $3_1 = 0, $5_1 = 0, $4_1 = 0;
  $1_1 = (($1_1 + 19 | 0) & -16 | 0) - 4 | 0;
  $3_1 = HEAP32[($0_1 + 1568 | 0) >> 2] | 0;
  if ($3_1) {
   $5_1 = $1_1 - 16 | 0;
   if (($5_1 | 0) == ($3_1 | 0)) {
    $4_1 = HEAP32[$3_1 >> 2] | 0;
    $1_1 = $5_1;
   }
  }
  $3_1 = ($2_1 & -16 | 0) - $1_1 | 0;
  if ($3_1 >>> 0 < 20 >>> 0) {
   return
  }
  $3_1 = $3_1 - 8 | 0;
  HEAP32[$1_1 >> 2] = $4_1 & 2 | 0 | ($3_1 | 1 | 0) | 0;
  HEAP32[($1_1 + 4 | 0) >> 2] = 0;
  HEAP32[($1_1 + 8 | 0) >> 2] = 0;
  $3_1 = ($1_1 + 4 | 0) + $3_1 | 0;
  HEAP32[$3_1 >> 2] = 2;
  HEAP32[($0_1 + 1568 | 0) >> 2] = $3_1;
  $11($0_1 | 0, $1_1 | 0);
 }
 
 function $27($0_1) {
  $0_1 = $0_1 | 0;
  var $1_1 = 0, $3_1 = 0, $2_1 = 0;
  block8 : {
   switch (HEAP32[($0_1 - 8 | 0) >> 2] | 0 | 0) {
   case 0:
    return;
   case 1:
    return;
   case 2:
    return;
   case 3:
    $28($0_1 | 0);
    return;
   case 4:
    $0(HEAP32[$0_1 >> 2] | 0 | 0);
    return;
   case 5:
    $1_1 = HEAP32[($0_1 + 4 | 0) >> 2] | 0;
    $2_1 = $1_1 + ((HEAP32[($0_1 + 12 | 0) >> 2] | 0) << 2 | 0) | 0;
    label : while (1) {
     if ($1_1 >>> 0 < $2_1 >>> 0) {
      $3_1 = HEAP32[$1_1 >> 2] | 0;
      if ($3_1) {
       $0($3_1 | 0)
      }
      $1_1 = $1_1 + 4 | 0;
      continue label;
     }
     break label;
    };
    $0(HEAP32[$0_1 >> 2] | 0 | 0);
    return;
   case 6:
    $28($0_1 | 0);
    return;
   case 7:
    return;
   default:
    break block8;
   };
  }
  wasm2js_trap();
 }
 
 function $28($0_1) {
  $0_1 = $0_1 | 0;
  $0(HEAP32[$0_1 >> 2] | 0 | 0);
 }
 
 function $29($0_1, $1_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  if ($1_1 >>> 0 >= (HEAP32[($0_1 + 12 | 0) >> 2] | 0) >>> 0) {
   fimport$0(10992 | 0, 11056 | 0, 114 | 0, 42 | 0);
   wasm2js_trap();
  }
  $0_1 = HEAP32[((HEAP32[($0_1 + 4 | 0) >> 2] | 0) + ($1_1 << 2 | 0) | 0) >> 2] | 0;
  if (!$0_1) {
   fimport$0(11104 | 0, 11056 | 0, 118 | 0, 40 | 0);
   wasm2js_trap();
  }
  return $0_1 | 0;
 }
 
 function $30() {
  global$1 = $14(1824 | 0) | 0;
  global$4 = $14(11520 | 0) | 0;
  global$5 = $14(11616 | 0) | 0;
 }
 
 function $31($0_1) {
  $0_1 = $0_1 | 0;
  var $2_1 = 0, $3_1 = 0, $6_1 = 0, $1_1 = 0, $4_1 = 0, $5_1 = 0, $88 = 0, $86 = 0, $72 = 0;
  $1_1 = $0_1;
  $2_1 = $0_1 >>> 8 | 0;
  $3_1 = $0_1 & 255 | 0;
  $2_1 = HEAP32[((((HEAPU8[($2_1 + 10060 | 0) >> 0] | 0) + (((Math_imul(HEAPU8[((Math_imul(HEAPU8[($2_1 + 6420 | 0) >> 0] | 0, 86) + 6420 | 0) + (($3_1 >>> 0) / (3 >>> 0) | 0) | 0) >> 0] | 0, HEAP32[(((($3_1 >>> 0) % (3 >>> 0) | 0) << 2 | 0) + 9088 | 0) >> 2] | 0) >>> 11 | 0) >>> 0) % (6 >>> 0) | 0) | 0) << 2 | 0) + 9100 | 0) >> 2] | 0;
  $0_1 = $2_1 & 255 | 0;
  $2_1 = $2_1 >> 8 | 0;
  block : {
   if ($0_1 >>> 0 < 2 >>> 0) {
    break block
   }
   $0_1 = $2_1 & 255 | 0;
   $2_1 = $2_1 >>> 8 | 0;
   label : while (1) {
    if ($0_1) {
     $6_1 = $0_1 >>> 1 | 0;
     $4_1 = (($6_1 + $2_1 | 0) << 1 | 0) + 10572 | 0;
     $5_1 = HEAPU8[$4_1 >> 0] | 0;
     if (($5_1 | 0) == ($3_1 | 0)) {
      $2_1 = HEAP32[(((HEAPU8[($4_1 + 1 | 0) >> 0] | 0) << 2 | 0) + 9100 | 0) >> 2] | 0;
      $0_1 = $2_1 & 255 | 0;
      $2_1 = $2_1 >> 8 | 0;
      if ($0_1 >>> 0 < 2 >>> 0) {
       break block
      }
      return $1_1 + 1 | 0 | 0;
     } else {
      if ($3_1 >>> 0 < $5_1 >>> 0) {
       $86 = $6_1
      } else {
       $2_1 = $2_1 + $6_1 | 0;
       $86 = $0_1 - $6_1 | 0;
      }
      $88 = $86;
     }
     $0_1 = $88;
     continue label;
    }
    break label;
   };
   return $1_1 | 0;
  }
  return $1_1 + ($2_1 & (0 - $0_1 | 0) | 0) | 0 | 0;
 }
 
 function $32($0_1) {
  $0_1 = $0_1 | 0;
  var $2_1 = 0, $1_1 = 0, $4_1 = 0, $6_1 = 0, $5_1 = 0, $8_1 = 0, $7_1 = 0, $3_1 = 0, $10_1 = 0, $127 = 0, $134 = 0, $185 = 0, $192 = 0, $9_1 = 0;
  $8_1 = $3($0_1 | 0) | 0;
  if (!$8_1) {
   return $0_1 | 0
  }
  $7_1 = $5($8_1 << 2 | 0 | 0, 2 | 0) | 0;
  label2 : while (1) {
   if ($3_1 >>> 0 < $8_1 >>> 0) {
    $1_1 = $0_1 + ($3_1 << 1 | 0) | 0;
    $2_1 = HEAPU16[$1_1 >> 1] | 0;
    if ($2_1 >>> 7 | 0) {
     block : {
      if (($2_1 - 55295 | 0) >>> 0 < 1025 >>> 0 & $3_1 >>> 0 < ($8_1 - 1 | 0) >>> 0 | 0) {
       $4_1 = HEAPU16[($1_1 + 2 | 0) >> 1] | 0;
       if (($4_1 - 56319 | 0) >>> 0 < 1025 >>> 0) {
        $3_1 = $3_1 + 1 | 0;
        $1_1 = $2_1;
        $2_1 = ($4_1 & 1023 | 0 | (($2_1 & 1023 | 0) << 10 | 0) | 0) + 65536 | 0;
        if ($2_1 >>> 0 >= 131072 >>> 0) {
         HEAP32[($7_1 + ($5_1 << 1 | 0) | 0) >> 2] = $1_1 | ($4_1 << 16 | 0) | 0;
         $5_1 = $5_1 + 1 | 0;
         break block;
        }
       }
      }
      if (($2_1 | 0) == (304 | 0)) {
       HEAP32[($7_1 + ($5_1 << 1 | 0) | 0) >> 2] = 50790505;
       $5_1 = $5_1 + 1 | 0;
      } else {
       if (($2_1 | 0) == (931 | 0)) {
        if ($8_1 >>> 0 > 1 >>> 0) {
         $1_1 = 0;
         $2_1 = $3_1;
         $4_1 = $2_1 - 30 | 0;
         $9_1 = ($4_1 | 0) >= (0 | 0) ? $4_1 : 0;
         block2 : {
          label : while (1) {
           if (($2_1 | 0) > ($9_1 | 0)) {
            $6_1 = -1;
            block1 : {
             if (($2_1 | 0) <= (0 | 0)) {
              break block1
             }
             $4_1 = HEAPU16[($0_1 + (($2_1 - 1 | 0) << 1 | 0) | 0) >> 1] | 0;
             $6_1 = $2_1 - 2 | 0;
             if (($4_1 & 64512 | 0 | 0) == (56320 | 0) & ($6_1 | 0) >= (0 | 0) | 0) {
              $10_1 = HEAPU16[($0_1 + ($6_1 << 1 | 0) | 0) >> 1] | 0;
              $6_1 = (($4_1 & 1023 | 0) + (($10_1 & 1023 | 0) << 10 | 0) | 0) + 65536 | 0;
              if (($10_1 & 64512 | 0 | 0) == (55296 | 0)) {
               break block1
              }
             }
             $6_1 = ($4_1 & 63488 | 0 | 0) == (55296 | 0) ? 65533 : $4_1;
            }
            if ($6_1 >>> 0 < 918e3 >>> 0) {
             $127 = $7(1844 | 0, $6_1 | 0) | 0
            } else {
             $127 = 0
            }
            if (!$127) {
             $4_1 = 0;
             if ($6_1 >>> 0 < 127370 >>> 0) {
              $134 = $7(4852 | 0, $6_1 | 0) | 0
             } else {
              $134 = 0
             }
             if (!$134) {
              break block2
             }
             $1_1 = 1;
            }
            $2_1 = $2_1 - ((($6_1 | 0) >= (65536 | 0)) + 1 | 0) | 0;
            continue label;
           }
           break label;
          };
          $4_1 = 0;
          if (!$1_1) {
           break block2
          }
          $2_1 = $3_1 + 1 | 0;
          $1_1 = $2_1 + 30 | 0;
          $4_1 = ($1_1 | 0) < ($8_1 | 0) ? $1_1 : $8_1;
          label1 : while (1) {
           if (($2_1 | 0) < ($4_1 | 0)) {
            $6_1 = $0_1 + ($2_1 << 1 | 0) | 0;
            $1_1 = HEAPU16[$6_1 >> 1] | 0;
            if (($1_1 & 64512 | 0 | 0) == (55296 | 0) & ($2_1 + 1 | 0 | 0) != ($8_1 | 0) | 0) {
             $6_1 = HEAPU16[($6_1 + 2 | 0) >> 1] | 0;
             if (($6_1 & 64512 | 0 | 0) == (56320 | 0)) {
              $1_1 = (($1_1 << 10 | 0) + $6_1 | 0) - 56613888 | 0
             }
            }
            if ($1_1 >>> 0 < 918e3 >>> 0) {
             $185 = $7(1844 | 0, $1_1 | 0) | 0
            } else {
             $185 = 0
            }
            if (!$185) {
             if ($1_1 >>> 0 < 127370 >>> 0) {
              $192 = $7(4852 | 0, $1_1 | 0) | 0
             } else {
              $192 = 0
             }
             $4_1 = !$192;
             break block2;
            }
            $2_1 = $2_1 + (($1_1 >>> 0 >= 65536 >>> 0) + 1 | 0) | 0;
            continue label1;
           }
           break label1;
          };
          $4_1 = 1;
         }
        } else {
         $4_1 = 0
        }
        HEAP16[($7_1 + ($5_1 << 1 | 0) | 0) >> 1] = $4_1 ? 962 : 963;
       } else {
        if (($2_1 - 9398 | 0) >>> 0 <= 25 >>> 0) {
         HEAP16[($7_1 + ($5_1 << 1 | 0) | 0) >> 1] = $2_1 + 26 | 0
        } else {
         $1_1 = ($31($2_1 | 0) | 0) & 2097151 | 0;
         if ($1_1 >>> 0 < 65536 >>> 0) {
          HEAP16[($7_1 + ($5_1 << 1 | 0) | 0) >> 1] = $1_1
         } else {
          $1_1 = $1_1 - 65536 | 0;
          HEAP32[($7_1 + ($5_1 << 1 | 0) | 0) >> 2] = $1_1 >>> 10 | 0 | 55296 | 0 | (($1_1 & 1023 | 0 | 56320 | 0) << 16 | 0) | 0;
          $5_1 = $5_1 + 1 | 0;
         }
        }
       }
      }
     }
    } else {
     HEAP16[($7_1 + ($5_1 << 1 | 0) | 0) >> 1] = $2_1 | ((($2_1 - 65 | 0) >>> 0 < 26 >>> 0) << 5 | 0) | 0
    }
    $3_1 = $3_1 + 1 | 0;
    $5_1 = $5_1 + 1 | 0;
    continue label2;
   }
   break label2;
  };
  return $34($7_1 | 0, $5_1 << 1 | 0 | 0) | 0 | 0;
 }
 
 function $33($0_1) {
  $0_1 = $0_1 | 0;
  if (!$0_1) {
   return
  }
  $0_1 = $0_1 - 20 | 0;
  if (($6($0_1 | 0) | 0 | 0) != (3 | 0)) {
   fimport$0(11568 | 0, 1712 | 0, 195 | 0, 5 | 0);
   wasm2js_trap();
  }
  $15($0_1 | 0);
  $9($0_1 | 0, global$1 | 0, global$2 | 0);
 }
 
 function $34($0_1, $1_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  var $2_1 = 0, $3_1 = 0, $5_1 = 0, $4_1 = 0, $6_1 = 0, $7_1 = 0, $8_1 = 0, $18_1 = 0, wasm2js_i32$0 = 0, wasm2js_i32$1 = 0;
  $2_1 = $0_1 - 20 | 0;
  if ($0_1 >>> 0 < 11684 >>> 0) {
   $3_1 = $5($1_1 | 0, HEAP32[($2_1 + 12 | 0) >> 2] | 0 | 0) | 0;
   $18_1 = $0_1;
   $0_1 = HEAP32[($2_1 + 16 | 0) >> 2] | 0;
   wasm2js_memory_copy($3_1, $18_1, $0_1 >>> 0 > $1_1 >>> 0 ? $1_1 : $0_1);
   return $3_1 | 0;
  }
  if ($1_1 >>> 0 > 1073741804 >>> 0) {
   fimport$0(1648 | 0, 1712 | 0, 143 | 0, 30 | 0);
   wasm2js_trap();
  }
  global$3 = global$3 - ($10($2_1 | 0) | 0) | 0;
  if (!global$0) {
   $12()
  }
  $3_1 = $1_1 + 16 | 0;
  $0_1 = $0_1 - 16 | 0;
  if ($0_1 >>> 0 < 11684 >>> 0) {
   $0_1 = $23(global$0 | 0, $13($0_1 | 0) | 0 | 0, $3_1 | 0) | 0
  } else {
   $4_1 = global$0;
   $0_1 = $13($0_1 | 0) | 0;
   block1 : {
    block : {
     $6_1 = $21($3_1 | 0) | 0;
     $7_1 = HEAP32[$0_1 >> 2] | 0;
     $5_1 = $7_1 & -4 | 0;
     if ($6_1 >>> 0 <= $5_1 >>> 0) {
      break block
     }
     $2_1 = ($0_1 + 4 | 0) + ((HEAP32[$0_1 >> 2] | 0) & -4 | 0) | 0;
     $8_1 = HEAP32[$2_1 >> 2] | 0;
     if ($8_1 & 1 | 0) {
      $5_1 = ($5_1 + 4 | 0) + ($8_1 & -4 | 0) | 0;
      if ($5_1 >>> 0 >= $6_1 >>> 0) {
       $8($4_1 | 0, $2_1 | 0);
       HEAP32[$0_1 >> 2] = $7_1 & 3 | 0 | $5_1 | 0;
       break block;
      }
     }
     $0_1 = $23($4_1 | 0, $0_1 | 0, $3_1 | 0) | 0;
     break block1;
    }
    $22($4_1 | 0, $0_1 | 0, $6_1 | 0);
   }
  }
  $0_1 = $0_1 + 20 | 0;
  $2_1 = $0_1 - 20 | 0;
  HEAP32[($2_1 + 16 | 0) >> 2] = $1_1;
  (wasm2js_i32$0 = $2($2_1 | 0) | 0, wasm2js_i32$1 = $2_1), HEAP32[(wasm2js_i32$0 + 8 | 0) >> 2] = wasm2js_i32$1;
  $16(HEAP32[($2_1 + 8 | 0) >> 2] | 0 | 0, $2_1 | 0);
  global$3 = ($10($2_1 | 0) | 0) + global$3 | 0;
  return $0_1 | 0;
 }
 
 function $35($0_1) {
  $0_1 = $0_1 | 0;
  var $1_1 = 0;
  if ($0_1) {
   $1_1 = $0_1 - 20 | 0;
   if (($6($1_1 | 0) | 0 | 0) == (3 | 0)) {
    fimport$0(11472 | 0, 1712 | 0, 181 | 0, 7 | 0);
    wasm2js_trap();
   }
   $15($1_1 | 0);
   $9($1_1 | 0, global$4 | 0, 3 | 0);
  }
  return $0_1 | 0;
 }
 
 function $36() {
  var $2_1 = 0, $6_1 = 0, $5_1 = 0, $3_1 = 0, scratch_6 = 0, scratch = 0;
  $0(1120 | 0);
  $0(1360 | 0);
  $0(1600 | 0);
  $0(10992 | 0);
  $0(11232 | 0);
  $0(11104 | 0);
  $0(1648 | 0);
  $0(11472 | 0);
  $0(11568 | 0);
  $3_1 = global$4;
  $2_1 = $2($3_1 | 0) | 0;
  label : while (1) {
   if (($2_1 | 0) != ($3_1 | 0)) {
    $6($2_1 | 0) | 0;
    $27($2_1 + 20 | 0 | 0);
    $2_1 = $2($2_1 | 0) | 0;
    continue label;
   }
   break label;
  };
  scratch_6 = !global$2;
  $5_1 = global$5;
  $2_1 = $2($5_1 | 0) | 0;
  label1 : while (1) {
   if (($2_1 | 0) != ($5_1 | 0)) {
    $6($2_1 | 0) | 0;
    $27($2_1 + 20 | 0 | 0);
    $2_1 = $2($2_1 | 0) | 0;
    continue label1;
   }
   break label1;
  };
  $6_1 = global$1;
  $2_1 = $2($6_1 | 0) | 0;
  label2 : while (1) {
   if (($2_1 | 0) != ($6_1 | 0)) {
    $6($2_1 | 0) | 0;
    scratch = $2($2_1 | 0) | 0;
    if ($2_1 >>> 0 < 11684 >>> 0) {
     HEAP32[($2_1 + 4 | 0) >> 2] = 0;
     HEAP32[($2_1 + 8 | 0) >> 2] = 0;
    } else {
     global$3 = global$3 - ($10($2_1 | 0) | 0) | 0;
     $2_1 = $2_1 + 4 | 0;
     if ($2_1 >>> 0 >= 11684 >>> 0) {
      if (!global$0) {
       $12()
      }
      $24(global$0 | 0, $13($2_1 | 0) | 0 | 0);
     }
    }
    $2_1 = scratch;
    continue label2;
   }
   break label2;
  };
  HEAP32[($6_1 + 4 | 0) >> 2] = $6_1;
  HEAP32[($6_1 + 8 | 0) >> 2] = $6_1;
  global$1 = $5_1;
  global$5 = $6_1;
  global$2 = scratch_6;
 }
 
 function $37() {
  var $0_1 = 0, $1_1 = 0, $2_1 = 0, $4_1 = 0, $3_1 = 0;
  $1_1 = $5(256 | 0, 7 | 0) | 0;
  wasm2js_memory_fill($1_1, 0, 256);
  label : while (1) {
   if (($0_1 | 0) < (256 | 0)) {
    $4($1_1 | 0, $0_1 | 0, $0_1 | 0);
    $0_1 = $0_1 + 1 | 0;
    continue label;
   }
   break label;
  };
  $0_1 = 0;
  label1 : while (1) {
   if (($0_1 | 0) < (256 | 0)) {
    $4_1 = ($1($1_1 | 0, $0_1 | 0) | 0) + $2_1 | 0;
    $2_1 = ($0_1 | 0) % (32 | 0) | 0;
    if ($2_1 >>> 0 >= (HEAP32[1132 >> 2] | 0) >>> 0) {
     fimport$0(10992 | 0, 11056 | 0, 114 | 0, 42 | 0);
     wasm2js_trap();
    }
    $3_1 = $1($1_1 | 0, $0_1 | 0) | 0;
    $2_1 = ($4_1 + (HEAPU8[($2_1 + (HEAP32[1124 >> 2] | 0) | 0) >> 0] | 0) | 0) & 255 | 0;
    $4($1_1 | 0, $0_1 | 0, $1($1_1 | 0, $2_1 | 0) | 0 | 0);
    $4($1_1 | 0, $2_1 | 0, $3_1 | 0);
    $0_1 = $0_1 + 1 | 0;
    continue label1;
   }
   break label1;
  };
  return $1_1 | 0;
 }
 
 function $38($0_1, $1_1) {
  $0_1 = $0_1 | 0;
  $1_1 = $1_1 | 0;
  var $2_1 = 0, $5_1 = 0, $3_1 = 0, $6_1 = 0, $4_1 = 0, $18_1 = 0, $7_1 = 0, $70 = 0, $72 = 0, $27_1 = 0, $58 = 0;
  $1_1 = $32($1_1 | 0) | 0;
  label : while (1) {
   if (($2_1 | 0) < (HEAP32[1372 >> 2] | 0 | 0)) {
    block1 : {
     block : {
      $5_1 = $29(1360 | 0, $2_1 | 0) | 0;
      $18_1 = 1;
      if (($5_1 | 0) == ($1_1 | 0)) {
       break block
      }
      $18_1 = 0;
      if (!$5_1 | !$1_1 | 0) {
       break block
      }
      $27_1 = $3($5_1 | 0) | 0;
      $6_1 = $3($1_1 | 0) | 0;
      $18_1 = 0;
      if (($27_1 | 0) != ($6_1 | 0)) {
       break block
      }
      $18_1 = !($17($1_1 | 0, 0 | 0, $5_1 | 0, $6_1 | 0) | 0);
     }
     if ($18_1) {
      $3_1 = 1;
      break block1;
     }
     $2_1 = $2_1 + 1 | 0;
     continue label;
    }
   }
   break label;
  };
  if (!$3_1) {
   $2_1 = 0;
   label1 : while (1) {
    if (($2_1 | 0) < (HEAP32[1612 >> 2] | 0 | 0)) {
     block2 : {
      $5_1 = $29(1600 | 0, $2_1 | 0) | 0;
      if (($3($1_1 | 0) | 0 | 0) > ($3($5_1 | 0) | 0 | 0)) {
       $6_1 = $3($1_1 | 0) | 0;
       $58 = ($6_1 | 0) > (536870910 | 0) ? 536870910 : $6_1;
       $6_1 = $3($5_1 | 0) | 0;
       $7_1 = $58 - $6_1 | 0;
       if (($7_1 | 0) < (0 | 0)) {
        $70 = 1
       } else {
        $70 = $17($1_1 | 0, $7_1 | 0, $5_1 | 0, $6_1 | 0) | 0
       }
       $72 = $70;
      } else {
       $72 = 1
      }
      if (!$72) {
       $3_1 = 1;
       break block2;
      }
      $2_1 = $2_1 + 1 | 0;
      continue label1;
     }
    }
    break label1;
   };
  }
  if (!$3_1) {
   return $18(0 | 0) | 0 | 0
  }
  $2_1 = $37() | 0;
  $3_1 = 0;
  $1_1 = 0;
  label2 : while (1) {
   if (($1_1 | 0) < (2048 | 0)) {
    $4_1 = ($4_1 + 1 | 0) & 255 | 0;
    $3_1 = (($1($2_1 | 0, $4_1 | 0) | 0) + $3_1 | 0) & 255 | 0;
    $5_1 = $1($2_1 | 0, $4_1 | 0) | 0;
    $4($2_1 | 0, $4_1 | 0, $1($2_1 | 0, $3_1 | 0) | 0 | 0);
    $4($2_1 | 0, $3_1 | 0, $5_1 | 0);
    $1_1 = $1_1 + 1 | 0;
    continue label2;
   }
   break label2;
  };
  $5_1 = HEAP32[($0_1 + 8 | 0) >> 2] | 0;
  $6_1 = $18($5_1 | 0) | 0;
  $1_1 = 0;
  label3 : while (1) {
   if (($1_1 | 0) < ($5_1 | 0)) {
    $4_1 = ($4_1 + 1 | 0) & 255 | 0;
    $3_1 = (($1($2_1 | 0, $4_1 | 0) | 0) + $3_1 | 0) & 255 | 0;
    $7_1 = $1($2_1 | 0, $4_1 | 0) | 0;
    $4($2_1 | 0, $4_1 | 0, $1($2_1 | 0, $3_1 | 0) | 0 | 0);
    $4($2_1 | 0, $3_1 | 0, $7_1 | 0);
    if ($1_1 >>> 0 >= (HEAP32[($0_1 + 8 | 0) >> 2] | 0) >>> 0) {
     fimport$0(10992 | 0, 11408 | 0, 167 | 0, 45 | 0);
     wasm2js_trap();
    }
    $7_1 = (($1($2_1 | 0, (($1($2_1 | 0, $4_1 | 0) | 0) + ($1($2_1 | 0, $3_1 | 0) | 0) | 0) & 255 | 0 | 0) | 0) ^ (HEAPU8[($1_1 + (HEAP32[($0_1 + 4 | 0) >> 2] | 0) | 0) >> 0] | 0) | 0) & 255 | 0;
    if ($1_1 >>> 0 >= (HEAP32[($6_1 + 8 | 0) >> 2] | 0) >>> 0) {
     fimport$0(10992 | 0, 11408 | 0, 178 | 0, 45 | 0);
     wasm2js_trap();
    }
    HEAP8[($1_1 + (HEAP32[($6_1 + 4 | 0) >> 2] | 0) | 0) >> 0] = $7_1;
    $1_1 = $1_1 + 1 | 0;
    continue label3;
   }
   break label3;
  };
  return $6_1 | 0;
 }
 
 function __wasm_ctz_i32(var$0) {
  var$0 = var$0 | 0;
  if (var$0) {
   return 31 - Math_clz32((var$0 + -1 | 0) ^ var$0 | 0) | 0 | 0
  }
  return 32 | 0;
 }
 
 function __wasm_rotl_i32(var$0, var$1) {
  var$0 = var$0 | 0;
  var$1 = var$1 | 0;
  var var$2 = 0;
  var$2 = var$1 & 31 | 0;
  var$1 = (0 - var$1 | 0) & 31 | 0;
  return ((-1 >>> var$2 | 0) & var$0 | 0) << var$2 | 0 | (((-1 << var$1 | 0) & var$0 | 0) >>> var$1 | 0) | 0 | 0;
 }
 
 bufferView = HEAPU8;
 initActiveSegments(imports);
 $30();
 function __wasm_memory_size() {
  return buffer.byteLength >> 16;
 }
 
 function __wasm_memory_grow(pagesToAdd) {
  pagesToAdd = pagesToAdd | 0;
  var oldPages = __wasm_memory_size() | 0;
  var newPages = oldPages + pagesToAdd | 0;
  if ((oldPages < newPages) && (newPages < 65536)) {
   var newBuffer = new ArrayBuffer(newPages << 16);
   var newHEAP8 = new Int8Array(newBuffer);
   newHEAP8.set(HEAP8);
   HEAP8 = new Int8Array(newBuffer);
   HEAP16 = new Int16Array(newBuffer);
   HEAP32 = new Int32Array(newBuffer);
   HEAPU8 = new Uint8Array(newBuffer);
   HEAPU16 = new Uint16Array(newBuffer);
   HEAPU32 = new Uint32Array(newBuffer);
   HEAPF32 = new Float32Array(newBuffer);
   HEAPF64 = new Float64Array(newBuffer);
   buffer = newBuffer;
   bufferView = HEAPU8;
  }
  return oldPages;
 }
 
 return {
  "decrypt": $38, 
  "__new": $5, 
  "__pin": $35, 
  "__unpin": $33, 
  "__collect": $36, 
  "__rtti_base": {
   get value() {
    return global$6;
   }, 
   set value(_global$6) {
    global$6 = _global$6;
   }
  }, 
  "memory": Object.create(Object.prototype, {
   "grow": {
    "value": __wasm_memory_grow
   }, 
   "buffer": {
    "get": function () {
     return buffer;
    }
    
   }
  })
 };
}

var retasmFunc = asmFunc({
  "env": env,
});
V.decrypt = retasmFunc.decrypt;
V.__new = retasmFunc.__new;
V.__pin = retasmFunc.__pin;
V.__unpin = retasmFunc.__unpin;
V.__collect = retasmFunc.__collect;
V.__rtti_base = retasmFunc.__rtti_base;
V.memory = retasmFunc.memory;

return V;
}

// ---------------------------------------------------------------------------
// AssemblyScript loader shim (mirrors the player bundle's helpers exactly)
// ---------------------------------------------------------------------------
var VC_MEM, VC_MOD, VC_PINNED;
function vcInit() {
  if (VC_MOD) return VC_MOD;
  VC_MOD = makeVidzeeCrypto();
  VC_MEM = VC_MOD.memory;
  VC_PINNED = {};
  return VC_MOD;
}
function vcPin(ptr) {
  if (ptr) {
    var n = VC_PINNED[ptr];
    if (n) VC_PINNED[ptr] = n + 1;
    else { VC_MOD.__pin(ptr); VC_PINNED[ptr] = 1; }
  }
  return ptr;
}
function vcUnpin(ptr) {
  if (ptr) {
    var n = VC_PINNED[ptr];
    if (n === 1) { VC_MOD.__unpin(ptr); delete VC_PINNED[ptr]; }
    else if (n) VC_PINNED[ptr] = n - 1;
  }
}
// Allocate a Uint8Array view (rtti 6) holding `bytes`, like the bundle's e()
function vcAllocBytes(bytes) {
  var G = bytes.length;
  var y = VC_MOD.__pin(VC_MOD.__new(G, 1)) >>> 0;
  var D = VC_MOD.__new(12, 6) >>> 0;
  var dv = new DataView(VC_MEM.buffer);
  dv.setUint32(D + 0, y, true);
  dv.setUint32(D + 4, y, true);
  dv.setUint32(D + 8, G, true);
  new Uint8Array(VC_MEM.buffer, y, G).set(bytes);
  VC_MOD.__unpin(y);
  return D;
}
// Allocate a UTF-16 string, like the bundle's i()
function vcAllocStr(str) {
  var B = str.length;
  var C = VC_MOD.__new(B << 1, 2) >>> 0;
  var I = new Uint16Array(VC_MEM.buffer);
  for (var G = 0; G < B; ++G) I[(C >>> 1) + G] = str.charCodeAt(G);
  return C;
}
// Read returned Uint8Array view (like the bundle's F())
function vcReadOut(outPtr) {
  var dv = new DataView(VC_MEM.buffer);
  var p = dv.getUint32(outPtr + 4, true);
  var len = dv.getUint32(outPtr + 8, true);
  return new Uint8Array(VC_MEM.buffer, p, len).slice();
}

var VC_HOST = 'player.vidzee.wtf';
function vidzeeWasmDecrypt(payloadBytes) {
  var V = vcInit();
  var A = vcPin(vcAllocBytes(payloadBytes));
  var B = vcAllocStr(VC_HOST);
  try {
    return vcReadOut(V.decrypt(A, B) >>> 0);
  } finally {
    vcUnpin(A);
  }
}

// ---------------------------------------------------------------------------
// Provider
// ---------------------------------------------------------------------------
var TMDB_API_KEY = '1865f43a0549ca50d341dd9ab8b29f49';
var TMDB_BASE_URL = 'https://api.themoviedb.org/3';
var CORE_API = 'https://core.vidzee.wtf';
var UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

function log(msg) { try { console.log('[Vidzee] ' + msg); } catch (e) {} }

function fetchJson(url, timeoutMs) {
  return fetch(url, { headers: { 'User-Agent': UA, 'Accept': 'application/json' } })
    .then(function (r) {
      if (!r.ok) throw new Error('HTTP ' + r.status + ' for ' + url);
      return r.json();
    });
}
function withTimeout(promise, ms, label) {
  return new Promise(function (resolve, reject) {
    var done = false;
    var t = setTimeout(function () { if (!done) { done = true; reject(new Error(label + ' timeout ' + ms + 'ms')); } }, ms);
    promise.then(function (v) { if (!done) { done = true; clearTimeout(t); resolve(v); } },
      function (e) { if (!done) { done = true; clearTimeout(t); reject(e); } });
  });
}

function normalizeQuality(label) {
  var s = String(label || '').toLowerCase();
  if (s.indexOf('4k') >= 0 || s.indexOf('2160') >= 0) return '4K';
  if (s.indexOf('1080') >= 0) return '1080p';
  if (s.indexOf('720') >= 0) return '720p';
  if (s.indexOf('480') >= 0) return '480p';
  if (s.indexOf('360') >= 0) return '360p';
  return 'Auto';
}

function getStreams(tmdbId, mediaType, season, episode) {
  mediaType = mediaType === 'tv' ? 'tv' : 'movie';
  season = season ? String(season) : '1';
  episode = episode ? String(episode) : '1';

  return new Promise(function (resolve) {
    var base;
    if (mediaType === 'movie') {
      base = CORE_API + '/streams/movie/' + tmdbId;
    } else {
      base = CORE_API + '/streams/tv/' + tmdbId + '/' + season + '/' + episode;
    }
    var langUrl = mediaType === 'movie'
      ? CORE_API + '/streams/languages/movie/' + tmdbId
      : CORE_API + '/streams/languages/tv/' + tmdbId + '/' + season + '/' + episode;

    withTimeout(
      fetchJson(langUrl, 15000).catch(function () { return { languages: [] }; }),
      18000, 'languages'
    ).then(function (langResp) {
      var langs = (langResp && langResp.languages) || [];
      // EN/TL only policy: keep dcloud (default) + English/Tagalog/Filipino lanes
      var servers = ['dcloud'];
      for (var i = 0; i < langs.length; i++) {
        var lname = String(langs[i] || '').toLowerCase();
        if (langs[i] && /english|tagalog|filipino|^fil$|^tl$/.test(lname)) {
          servers.push('v4:' + langs[i]);
        }
      }
      log('servers: ' + servers.join(', '));

      var jobs = servers.map(function (srv) {
        var url = base + '?s=' + encodeURIComponent(srv) + '&e=1';
        return withTimeout(
          fetch(url, { headers: { 'User-Agent': UA, 'Accept': 'application/json', 'Origin': 'https://player.vidzee.wtf', 'Referer': 'https://player.vidzee.wtf/' } })
            .then(function (r) { return r.ok ? r.json() : null; })
            .then(function (j) {
              if (!j || !j.c) return null;
              var bytes;
              try { bytes = atob(j.c); } catch (e) { return null; }
              var u8 = new Uint8Array(bytes.length);
              for (var k = 0; k < bytes.length; k++) u8[k] = bytes.charCodeAt(k);
              var plain;
              try { plain = vidzeeWasmDecrypt(u8); } catch (e) { log('decrypt fail: ' + e.message); return null; }
              var text = '';
              try { text = new TextDecoder ? new TextDecoder().decode(plain) : bufferToString(plain); } catch (e) { return null; }
              var obj;
              try { obj = JSON.parse(text); } catch (e) { return null; }
              if (!obj || !obj.url) return null;
              return {
                server: srv,
                language: obj.language || (srv.indexOf('v4:') === 0 ? srv.slice(3) : 'Auto'),
                url: obj.url,
                headers: obj.headers || null
              };
            })
            .catch(function () { return null; }),
          20000, srv
        ).catch(function () { return null; });
      });

      return Promise.all(jobs).then(function (results) {
        var streams = [];
        for (var i = 0; i < results.length; i++) {
          var r = results[i];
          if (!r || !r.url) continue;
          var label = r.server === 'dcloud' ? 'DCloud' : (r.language || r.server);
          var headers = { 'User-Agent': UA };
          if (r.headers && r.headers.Referer) headers['Referer'] = r.headers['Referer'];
          streams.push({
            name: 'Vidzee',
            title: 'Vidzee ' + label,
            url: r.url,
            quality: normalizeQuality(r.language),
            headers: headers
          });
        }
        log('Returning ' + streams.length + ' stream(s)');
        resolve(streams);
      });
    }).catch(function (e) {
      log('error: ' + e.message);
      resolve([]);
    });
  });
}

// QuickJS-safe UTF-8 decode fallback (no TextDecoder in some builds)
function bufferToString(u8) {
  var out = '', i = 0;
  while (i < u8.length) {
    var b = u8[i];
    if (b < 0x80) { out += String.fromCharCode(b); i++; }
    else if (b < 0xe0) { out += String.fromCharCode(((b & 0x1f) << 6) | (u8[i + 1] & 0x3f)); i += 2; }
    else if (b < 0xf0) {
      out += String.fromCharCode(((b & 0x0f) << 12) | ((u8[i + 1] & 0x3f) << 6) | (u8[i + 2] & 0x3f)); i += 3;
    } else {
      var cp = ((b & 0x07) << 18) | ((u8[i + 1] & 0x3f) << 12) | ((u8[i + 2] & 0x3f) << 6) | (u8[i + 3] & 0x3f);
      cp -= 0x10000;
      out += String.fromCharCode(0xd800 + (cp >> 10), 0xdc00 + (cp & 0x3ff));
      i += 4;
    }
  }
  return out;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { getStreams: getStreams };
} else {
  global.getStreams = getStreams;
}

/* ===== nvio post-filter v1.0 (auto-injected) ============================
   Rules (per user request 2026-09):
   1. Language gate: only English / Tagalog (Filipino) audio lanes are kept.
      Streams explicitly tagged with another audio language (hindi, tamil,
      spanish, arabic, korean, ...) are dropped unless an allowed language
      is also present (dual/multi audio) or no language is tagged at all.
      Subtitle-only tokens (ESub, HindiSub, ...) are ignored by the gate.
   2. Quality gate: unknown/"Auto" resolutions are probed from the HLS
      master playlist; everything below 720p, CAM/telesync, and still-
      unknown rows are dropped. Survivors are labeled 720p/1080p/1440p/4K.
   3. Dedupe: exact URL, then normalized URL (query stripped, torrent
      info-hash), then identical name+quality rows. A short-TTL global
      registry also removes the same URL reported by two different
      providers (cross-provider duplicates).
   Opt-out: set SCRAPER_SETTINGS.postFilter = false.
======================================================================== */
(function () {
  var PROVIDER = "vidzee";
  var G = typeof globalThis !== "undefined" ? globalThis : typeof global !== "undefined" ? global : this;
  function settings() {
    try { return (G && G.SCRAPER_SETTINGS) || {}; } catch (e) { return {}; }
  }
  function hasTimers() { return typeof setTimeout === "function" && typeof clearTimeout === "function"; }

  /* ---------- quality ---------- */
  function normQ(q) {
    var s = String(q == null ? "" : q).toLowerCase();
    if (!s) return "";
    if (/8k/.test(s)) return "4K";
    if (/2160|4k|uhd/.test(s)) return "4K";
    if (/1440/.test(s)) return "1440p";
    if (/1080|fhd/.test(s)) return "1080p";
    if (/720/.test(s)) return "720p";
    if (/480|360|240|\bsd\b/.test(s)) return "CAM";
    if (/cam|telesync|telecine|\bts\b|\btc\b|screener|dvdscr/.test(s)) return "CAM";
    return "";
  }
  function qFromText(text) {
    var s = String(text || "");
    var m = s.match(/(\d{3,4})\s*p/i);
    if (m) {
      var n = parseInt(m[1], 10);
      if (n >= 2100) return "4K";
      if (n >= 1300) return "1440p";
      if (n >= 1000) return "1080p";
      if (n >= 640) return "720p";
      return "CAM";
    }
    if (/\b8k\b/i.test(s) || /2160|4k|uhd/i.test(s)) return "4K";
    if (/1440p/i.test(s)) return "1440p";
    if (/cam|telesync|telecine|\bts\b|\btc\b|screener|dvdscr/i.test(s)) return "CAM";
    if (/480p|360p|240p|\bsd\b|\bdvdrip\b/i.test(s)) return "CAM";
    if (/\bhd\b/i.test(s)) return "720p";
    return "";
  }
  var qualCache = G.__NV_QUAL_CACHE__ || (G.__NV_QUAL_CACHE__ = {});
  function probeM3u8(url, headers) {
    var now = Date.now();
    var c = qualCache[url];
    if (c && now - c.t < (c.q ? 15 * 60 * 1000 : 3 * 60 * 1000)) {
      return Promise.resolve(c.q);
    }
    var opts = { headers: Object.assign({}, headers || {}) };
    var p = fetch(url, opts).then(function (r) {
      return r.ok ? r.text() : "";
    }).then(function (t) {
      var q = "";
      if (t && t.indexOf("#EXTM3U") !== -1) {
        var best = 0, re = /RESOLUTION=(\d+)x(\d+)/gi, m;
        while ((m = re.exec(t)) !== null) {
          var h = parseInt(m[2], 10);
          if (h > best) best = h;
        }
        if (best >= 2100) q = "4K";
        else if (best >= 1300) q = "1440p";
        else if (best >= 1000) q = "1080p";
        else if (best >= 640) q = "720p";
        else if (best > 0) q = "CAM";
      }
      qualCache[url] = { t: now, q: q };
      return q;
    }).catch(function () { qualCache[url] = { t: now, q: "" }; return ""; });
    if (hasTimers()) {
      p = Promise.race([p, new Promise(function (res) {
        var timer = setTimeout(function () { res(""); }, 6000);
        if (typeof timer === "object" && typeof timer.unref === "function") timer.unref();
      })]);
    }
    return p;
  }

  /* ---------- language gate ---------- */
  var BLOCK_RE = new RegExp(
    "\\b(hindi|hin|tamil|telugu|malayalam|mallu|kannada|bengali|bangla|punjabi|marathi|bhojpuri|gujarati|" +
    "odia|assamese|nepali|urdu|sinhala|arabic|ara|farsi|persian|turkish|turkce|espanol|spanish|latino|" +
    "castellano|french|vostfr|german|deutsch|russian|korean|kor|japanese|jpn|chinese|mandarin|cantonese|" +
    "thai|vietnamese|indonesian|bahasa|portuguese|brasileiro|italian|polish|ukrainian|hebrew|" +
    "hungarian|romanian|dutch|flemish|greek|czech|swedish|danish|norwegian|finnish|org)\\b", "i");
  var ALLOW_RE = /\b(english|eng|tagalog|filipino)\b/i;
  var SUB_RE = /\b[a-z0-9]{0,12}subs?\b/gi;
  // NOTE: gate runs on the stream TITLE only (release names / labels).
  // Provider names (e.g. "MallumV") must not trigger the language gate.
  function langAllowed(titleText) {
    var t = String(titleText || "").replace(SUB_RE, " ");
    if (BLOCK_RE.test(t)) return ALLOW_RE.test(t);
    return true;
  }

  /* ---------- dedupe ---------- */
  function normUrl(u) {
    var s = String(u || "");
    if (/^magnet:/i.test(s)) {
      var m = s.match(/btih:([a-z0-9]+)/i);
      return "m:" + (m ? m[1].toLowerCase() : s.slice(0, 80));
    }
    return s.replace(/[#?].*$/, "").replace(/\/+$/, "");
  }
  var SEEN = G.__NV_SEEN_URLS__ || (G.__NV_SEEN_URLS__ = {});
  // SEEN[nu] = { exp: <ts>, owner: <provider> }
  // - same URL from a DIFFERENT provider within TTL -> dropped (cross-provider dup)
  // - same provider re-querying its own URL -> allowed (repeat opens must still
  //   return rows) and its claim is refreshed
  function claim(nu, now, owner) {
    if (!nu) return true;
    var e = SEEN[nu];
    if (e && e.exp > now && e.owner !== owner) return false;
    SEEN[nu] = { exp: now + 120000, owner: owner };
    return true;
  }

  /* ---------- main ---------- */
  function rank(q) {
    if (q === "4K") return 4;
    if (q === "1440p") return 3.5;
    if (q === "1080p") return 3;
    if (q === "720p") return 2;
    return 0;
  }
  function postProcess(list) {
    var now = Date.now();
    var kept = [];
    var probes = [];
    var rows = [];
    (list || []).forEach(function (s, i) {
      if (!s || !s.url) return;
      if (!langAllowed(s.title)) return;
      var text = (s.name || "") + " " + (s.title || "");
      var isMagnet = /^magnet:/i.test(String(s.url));
      var q = normQ(s.quality) || normQ(String(s.title || "").split("\n")[0]) || qFromText(text);
      var isHlsLike = /m3u8/i.test(String(s.url)) ||
        (!/\.(mp4|mkv|avi|mov|webm|ts|flv|m4v|mp3|aac)(\?|$)/i.test(String(s.url.split("?")[0])) && /^https?:/i.test(String(s.url)));
      if (!q && !isMagnet && isHlsLike) {
        rows.push({ s: s, i: i });
        probes.push(probeM3u8(String(s.url), s.headers));
      } else {
        rows.push({ s: s, i: i });
        probes.push(Promise.resolve(q));
      }
    });
    return Promise.all(probes).then(function (qs) {
      var ranked = [];
      rows.forEach(function (row, k) {
        var q = qs[k];
        if (!q) return; // unknown resolution -> removed
        if (q === "CAM") return; // cam / sd / sub-720 -> removed
        row.s.quality = q;
        ranked.push({ s: row.s, i: row.i, q: q });
      });
      // best first so dedupe keeps the strongest duplicate (stable)
      ranked.sort(function (a, b) {
        var r = rank(b.q) - rank(a.q);
        if (r !== 0) return r;
        return a.i - b.i;
      });
      var seenLocal = {}, out = [];
      ranked.forEach(function (row) {
        var s = row.s;
        var nu = normUrl(s.url);
        if (seenLocal[nu]) return;
        if (!claim(nu, now, PROVIDER)) return; // already reported by a different provider
        seenLocal[nu] = 1;
        out.push(s);
      });
      return out.slice(0, 40);
    }).catch(function () { return (list || []).slice(0, 40); });
  }

  var __orig = null;
  try { __orig = module.exports && module.exports.getStreams; } catch (e) { __orig = null; }
  if (typeof __orig === "function") {
    module.exports.getStreams = function () {
      var args = Array.prototype.slice.call(arguments), self = this;
      function finish(v) {
        if (settings().postFilter === false) return v;
        try { return postProcess(Array.isArray(v) ? v : []); }
        catch (e) { return Array.isArray(v) ? v : []; }
      }
      try {
        var r = __orig.apply(self, args);
        if (r && typeof r.then === "function") {
          return r.then(function (v) { return finish(v); }, function () { return []; });
        }
        return finish(r);
      } catch (e) { return Promise.resolve([]); }
    };
  }
})();
